spring:	
  h2:	
    console:	
      enabled: true	
      path: /h2-console	


  datasource:	
    url: jdbc:h2:~/productmicroservice	
    driverClassName: org.h2.Driver	
    username: sa	
    password:	

  jpa:	
    hibernate:	
        ddl-auto: update	
      show-sql: true	
      properties.generate-statistics: true	


eureka:	
  client:	
    register-with-eureka: true	
    fetch-registry: true	
    serviceUrl:	
      defaultZone: http://${eureka.instance.hostname}:1111/eureka	


  instance:	
    hostname: localhost	


management:	
  server: 	
    port: 1234	

  endpoints:	
    web:	
      exposure:	
        include: "*"	

welcome:	
  message: "Refresh from GIT ZUUL!!!"